[package]
name = "zkstandard"
version = "0.1.0"
authors = ["Aurélien Nicolas <aurel@qed-it.com>"]

[dependencies]
capnp = "0.9.4"
capnp-futures = "0.9.0"
capnp-rpc = "0.9.0"

[build-dependencies]
capnpc = "0.9"
