[package]
name = "zkstandard"
version = "0.1.0"
authors = ["Aurélien Nicolas <aurel@qed-it.com>"]
build = "build.rs"

[dependencies]
libloading = "0.5.0"
flatbuffers = "0.5.0"

[build-dependencies]
cc = "1.0.28"