[package]
name = "zkinterface"
version = "0.1.0"
authors = ["Aurélien Nicolas <aurel@qed-it.com>"]
build = "build.rs"
links = "zkinterface"

[features]
# Whether to regenerate code from zkinterface.fbs. Requires the Flatbuffers compiler.
flatc = []
# Whether to compile, include, and test C++ code. Requires cmake.
cpp = []

[dependencies]
flatbuffers = "0.5.0"

[build-dependencies]
regex = "1"
cmake = "0.1"
