[package]
name = "zkinterface"
version = "1.0.3"
authors = ["Aurélien Nicolas <aurel@qed-it.com>"]
license = "MIT"
build = "build.rs"
links = "zkinterface"
description = "An implementation of zkInterface"
homepage = "https://github.com/QED-it/zkinterface"
repository = "https://github.com/QED-it/zkinterface/rust"
documentation = "https://github.com/QED-it/zkinterface/blob/master/zkInterface.pdf"
keywords = ["zero-knowledge", "zkproof", "cryptography"]

[features]
# Whether to regenerate code from zkinterface.fbs. Requires the Flatbuffers compiler.
fbs = []
# Whether to compile, include, and test C++ code. Requires cmake.
cpp = []

[dependencies]
flatbuffers = "0.5.0"

[build-dependencies]
regex = "1"
cmake = "0.1"
